#!/usr/bin/env python3
import requests, time, sys
from requests.auth import HTTPBasicAuth
import pprint
import click
import json


class OpenDtu:

    def __init__(self, host, user, pw):
        self.auth = HTTPBasicAuth(user, pw)
        self.headers  = {'Content-Type': 'application/x-www-form-urlencoded'}
        self.host = f'http://{host}/api/'

    def get(self, path):
        return requests.get(url = f'{self.host}{path}').json()


 
@click.group()
def cli():
    pass


@cli.command("list-inverters")
@click.option("--opendtu_host", "-h", required=True, help="openDTU hostname/ip")
@click.option("--opendtu_user", "-u", required=True, help="openDTU user")
@click.option("--opendtu_pw", "-p", required=True, help="openDTU password")
@click.option("--raw", "-r", is_flag=True, default=False, help="Raw output")
def list_inverters(opendtu_host, opendtu_user, opendtu_pw, raw):
    livedata = OpenDtu(opendtu_host, opendtu_user, opendtu_pw).get("livedata/status/inverters")

    if raw:
        print(json.dumps(livedata))


if __name__ == "__main__":
    cli()
  


# Diese Daten müssen angepasst werden:
#serial = "112100000000" # Seriennummer des Hoymiles Wechselrichters
#maximum_wr = 300 # Maximale Ausgabe des Wechselrichters
#minimum_wr = 100 # Minimale Ausgabe des Wechselrichters

#dtu_ip = '192.168.23.199' # IP Adresse von OpenDTU
#dtu_nutzer = 'admin' # OpenDTU Nutzername
#dtu_passwort = '95Virtual$' # OpenDTU Passwort

#shelly_ip = '192.168.23.192' # IP Adresse von Shelly 3EM


#try:
    # Nimmt Daten von der openDTU Rest-API und übersetzt sie in ein json-Format
#    r = requests.get(url = f'http://{dtu_ip}/api/livedata/status/inverters' ).json()

#    pprint.pprint(r)

    # Selektiert spezifische Daten aus der json response
#    reachable   = r['inverters'][0]['reachable'] # Ist DTU erreichbar?
#    producing   = int(r['inverters'][0]['producing']) # Produziert der Wechselrichter etwas?
#    altes_limit = int(r['inverters'][0]['limit_absolute']) # Altes Limit
#    power_dc    = r['inverters'][0]['AC']['0']['Power DC']['v']  # Lieferung DC vom Panel
#    power       = r['inverters'][0]['AC']['0']['Power']['v'] # Abgabe BKW AC in Watt
#except:
#    print('Fehler beim Abrufen der Daten von openDTU')

#try:
#    # Nimmt Daten von der Shelly 3EM Rest-API und übersetzt sie in ein json-Format
#    phase_a     = requests.get(f'http://{shelly_ip}/emeter/0', headers={'Content-Type': 'application/json'}).json()['power']
#    phase_b     = requests.get(f'http://{shelly_ip}/emeter/1', headers={'Content-Type': 'application/json'}).json()['power']
#    phase_c     = requests.get(f'http://{shelly_ip}/emeter/2', headers={'Content-Type': 'application/json'}).json()['power']
#    grid_sum    = phase_a + phase_b + phase_c # Aktueller Bezug - rechnet alle Phasen zusammennt
#    print(grid_sum)
#except:
#    print('Fehler beim Abrufen der Daten von Shelly 3EM')

